### PR TITLE
chore: update test for post form

### PR DESCRIPTION
**Pull request by Genora**
The test failed : likely because  the values that were inputted did not trigger the preview button to show up 
Screen Shot 2020-11-22 at 11 04 39 PM
Screen Shot 2020-11-22 at 11 04 17 PM

### CODE REVIEW

**Comment by metasansana** [comment]
Two things going on here:
1) The button is clearly there on screen, so it exists, your query selector is wrong though try `.preview-button` instead. Pay attention to the error messages.
2) The button is supposed to become enabled when all the fields are filled, i'll have to look into this further.

**Review by metasansana — CHANGES_REQUESTED** [review]
See my comment in the conversation tab.

**Comment by Genora** [comment]
1. I used '.-preview-button' which I got from inspecting the CSS.
2. I believe that's the issue - when the test generated fills out the form, the button is not enabled. However when I fille dit out manually in the test browser, the button became enabled

**Comment by metasansana** [comment]
@

>     1. I used '.-preview-button' which I got from inspecting the CSS.
> 
>     2. I believe that's the issue - when the test generated fills out the form, the button is not enabled. However when I fille dit out manually in the test browser, the button became enabled

Yeah we'll sort this out next meet.

**Comment by metasansana** [comment]
Closing this as it's all stale now.

**Pull request closed without merging**
