### PR TITLE
chore: update validation to validators

### PR DESCRIPTION
**Pull request by Genora**

### CODE REVIEW

**Review by metasansana — CHANGES_REQUESTED** [review]
You forgot to update `@quenk/dagen-commons` and rebuild.

Looks like npm now supports an update command. Try it and see what it breaks:
https://docs.npmjs.com/updating-packages-downloaded-from-the-registry

**Comment by metasansana** [comment]
Any progress on this?

**Comment by Genora** [comment]
I just realized I can't send a screenshot of the error here

**Comment by metasansana** [comment]
> Screen Shot 2020-11-12 at 11 21 40 PM
> An example of the error

Looks like the Admin type needs to be added to the list of imports in the schema file. Should be there already though.

**Comment by metasansana** [comment]
> You forgot to update `@quenk/dagen-commons` and rebuild.
> 
> Looks like npm now supports an update command. Try it and see what it breaks:
> https://docs.npmjs.com/updating-packages-downloaded-from-the-registry

Did you do this?

**Comment by Genora** [comment]
Yes, I did. I've commented on the new PR. I'd like to close this one so as not to cause confusion.

**Comment by metasansana** [comment]
Cancelling this PR.

**Pull request closed without merging**
