### PR TITLE
chore: updated validation to validators

### PR DESCRIPTION
**Pull request by Genora**
Ran into errors when I updated validation to validators in this syntax 'validation:imports" . This occurred for post.ts, login.ts and  candidatePost.ts files. This happened even after running npm update @quenk/dagen-commons

### CODE REVIEW

**Comment by metasansana** [comment]
Which one of these is the PR? This or #53. Also looks like you included the changes for your test PR in here by mistake.

**Comment by Genora** [comment]
This one, I started from scratch instead of modifying the old PR. How do I remove the changes from the test PR?

**Comment by metasansana** [comment]
@Genora I recommend you just start over. Copy the files you changed somewhere, create a new branch, then copy restore them. Note: the files you changed, not the files created by the build process. Let `make` regenerate that for you.

**Comment by metasansana** [comment]
Closing this as it's all stale now.

**Pull request closed without merging**
